# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: recommendation 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "recommendation"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["id774"]
  s.date = "2013-12-13"
  s.description = "Collaborative filtering for recommender system"
  s.email = "idnanashi@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "README.md",
    "Rakefile",
    "VERSION",
    "demo.rb",
    "doc/AUTHORS",
    "doc/COPYING",
    "doc/COPYING.LESSER",
    "doc/ChangeLog",
    "doc/LICENSE",
    "doc/README",
    "lib/recommendation.rb",
    "lib/recommendation/recommender.rb",
    "lib/recommendation/version.rb",
    "recommendation.gemspec",
    "script/build",
    "spec/lib/recommendation/recommender_spec.rb",
    "spec/lib/recommendation_spec.rb",
    "spec/spec_helper.rb",
    "vendor/.gitkeep"
  ]
  s.homepage = "http://github.com/id774/recommendation"
  s.licenses = ["GPL"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "recommendation"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

